"""empty message

Revision ID: dc1b3b3e1711
Revises: 885bcabc0d68
Create Date: 2023-04-21 20:58:08.741008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1b3b3e1711'
down_revision = '885bcabc0d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
